// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "IntentCept",
  description: "Generated by create next app",
};

import localFont from "next/font/local";


// Example: local font file stored in /public/fonts/
const nosifer = localFont({
  src: "./fonts/Nosifer-Regular.ttf",
  display: "swap",
});


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={nosifer.className}>
      <body className="font-[var(--font-nosifer)]">
        {children}
        <SpeedInsights/>
      </body>
    </html>
  );
}




